name: Node.js CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set permissions for Jest (only on GitHub)
      run: chmod +x ./node_modules/.bin/jest
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
